name: network_ninja
description: A powerful network logger library with floating bubble UI for monitoring API calls in Flutter applications
version: 1.1.1
repository: https://github.com/BlueMatterIn/network_ninja
issue_tracker: https://github.com/BlueMatterIn/network_ninja/issues
license: MIT

# Exclude docs folder from package (used for GitHub Pages)
exclude:
  - docs/

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  intl: ^0.20.2
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: ^1.24.0
  mockito: ^5.4.4
  build_runner: ^2.4.8
