name: network_ninja
description: A powerful network logger library with floating bubble UI for monitoring API calls in Flutter applications
version: 1.0.0
homepage: https://github.com/yourusername/network_ninja
repository: https://github.com/yourusername/network_ninja
issue_tracker: https://github.com/yourusername/network_ninja/issues
documentation: https://pub.dev/documentation/network_ninja
license: MIT

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  intl: ^0.20.2
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: ^1.24.0
  mockito: ^5.4.4
  build_runner: ^2.4.8

flutter:
# No assets needed for this package
